name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download NW.js
      run: |
        curl -L -o nw.zip https://dl.nwjs.io/v0.48.0/nwjs-v0.48.0-win-ia32.zip
        Expand-Archive -Path nw.zip -DestinationPath nwjs
    
    - name: Create app folder
      run: mkdir app
    
    - name: Copy app files
      run: |
        copy index.html app\
        copy package.json app\
        Get-ChildItem -Path . -Filter *.css | Copy-Item -Destination app\
        Get-ChildItem -Path . -Filter *.js | Copy-Item -Destination app\
    
    - name: Copy NW.js files
      run: |
        robocopy nwjs\nwjs-v0.48.0-win-ia32 app /E
        exit 0
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: myapp
        path: app/
